@startuml

'==== DOMINIO ====

class Clima {
    +temperatura : double
    +humedad : int
    +descripcion : String
    +fechaHora : LocalDateTime
}

'Una alerta generada que contiene los datos necesarios para notificar
class Alerta {
    -clima : Clima
    -fecha : LocalDateTime
}

'==== WEATHER API ====
'Cliente capaz de consultar un proveedor meteorológico

'Facil cambiar de proovedor
interface WeatherApiClient {
    +obtenerClimaActual() : WeatherResponse
}

class WeatherApiClientImpl

WeatherApiClientImpl ..|> WeatherApiClient

'Dto del JSON recibido
class WeatherResponse {
    +temperatura : double
    +humedad  : int
    +descripcion  : String
}

'==== SERVICES ====
'Obtiene un Clima, lo analiza, crea una alerta y avisa al GestorAlertas
class AnalizadorClimatico {
    -estrategia : EstrategiaAlerta
    -gestorAlertas : GestorAlertas

    +analizar(clima)
}

class RegistroClimatico {
    -historial : List<Clima>

    +guardar(clima)
    +obtenerUltimo() : Clima
}

'==== PATRÓN FACADE ====
'Adapta el clima obtenido al modelo interno

class ClimaFacade {
    -weatherApiClient : WeatherApiClient
    -climaAdapter : ClimaAdapter
    -registroClimatico : RegistroClimatico
    -analizadorClimatico : AnalizadorClimatico

    +actualizarClima()
    +analizarUltimoClima()
}

'==== PATRÓN ADAPTER ====
'Convierte un WeatherResponse en un Clima del dominio

interface ClimaAdapter {
    +adaptar(response: WeatherResponse) : Clima
}

class WeatherApiAdapter

WeatherApiAdapter ..|> ClimaAdapter

'==== PATRÓN STRATEGY ====

interface EstrategiaAlerta {
    +esCondicionCritica(clima: Clima): boolean
}

class EstrategiaTemperaturaHumedad

EstrategiaTemperaturaHumedad ..|> EstrategiaAlerta

'==== PATRÓN OBSERVER ====

'Representa cualquier componente interesado en enterarse de una alerta
interface ObservadorAlerta {
    +actualizar(alerta)
}

'Observador concreto
class EmailNotifier

EmailNotifier ..|> ObservadorAlerta

'Contiene una lista de observadores para informar
class GestorAlertas {
    +suscribir(observador)
    +desuscribir(observador)
    +notificar(alerta)
}

'==== RELACIONES ====

ClimaFacade --> WeatherApiClient
ClimaFacade --> ClimaAdapter
ClimaFacade --> RegistroClimatico
ClimaFacade --> AnalizadorClimatico

WeatherApiClient --> WeatherResponse
WeatherApiAdapter --> WeatherResponse
WeatherApiAdapter --> Clima

RegistroClimatico --> Clima

AnalizadorClimatico --> EstrategiaAlerta
AnalizadorClimatico --> GestorAlertas
'Crea
AnalizadorClimatico ..> Alerta

GestorAlertas o--> ObservadorAlerta
GestorAlertas --> Alerta

@enduml